# Generated by Django 5.1.7 on 2025-03-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_patient_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='discharge_status',
            field=models.BooleanField(default=False),
        ),
    ]
