# Generated by Django 5.1.7 on 2025-03-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_patient_discharge_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='payment_done',
            field=models.BooleanField(default=False),
        ),
    ]
