# Generated by Django 5.1.7 on 2025-03-27 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_room_alter_appointment_doctorid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineprescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.patient'),
        ),
    ]
