# Generated by Django 5.1.7 on 2025-03-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_prescription_delete_medicineprescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdischargedetails',
            name='prescribed_medicines',
            field=models.TextField(blank=True, null=True),
        ),
    ]
