# Generated by Django 5.1.7 on 2025-03-30 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_room_roombooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roombooking',
            name='room',
        ),
        migrations.RemoveField(
            model_name='roombooking',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='RoomBooking',
        ),
    ]
