# Generated by Django 5.1.7 on 2025-03-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_room_roombooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='price_per_day',
        ),
        migrations.RemoveField(
            model_name='roombooking',
            name='status',
        ),
        migrations.RemoveField(
            model_name='roombooking',
            name='total_price',
        ),
        migrations.AddField(
            model_name='roombooking',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
