# Generated by Django 5.1.7 on 2025-03-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_room_price_per_day_remove_roombooking_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roombooking',
            old_name='check_in_date',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='roombooking',
            name='check_out_date',
        ),
        migrations.RemoveField(
            model_name='roombooking',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='roombooking',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('General', 'General'), ('Private', 'Private'), ('ICU', 'ICU')], max_length=50),
        ),
    ]
