# Generated by Django 5.1.7 on 2025-03-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_emergencyalert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencyalert',
            name='is_resolved',
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Responded', 'Responded')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='emergencyalert',
            name='emergency_type',
            field=models.CharField(choices=[('Heart Attack', 'Heart Attack'), ('Accident', 'Accident'), ('Breathing Issue', 'Breathing Issue'), ('Other', 'Other')], default='Other', max_length=100),
        ),
        migrations.AlterField(
            model_name='emergencyalert',
            name='location',
            field=models.CharField(help_text="Patient's Current Location", max_length=255),
        ),
    ]
