# Generated by Django 5.1.7 on 2025-03-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_remove_emergencyalert_is_resolved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencyalert',
            name='status',
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emergencyalert',
            name='emergency_type',
            field=models.CharField(choices=[('Heart Attack', 'Heart Attack'), ('Accident', 'Accident'), ('Breathing Issue', 'Breathing Issue'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='emergencyalert',
            name='location',
            field=models.TextField(),
        ),
    ]
