# Generated by Django 5.1.7 on 2025-03-30 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_ambulancebooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AmbulanceBooking',
        ),
    ]
