# Generated by Django 5.1.7 on 2025-03-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_labtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdischargedetails',
            name='total_lab_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
