# Generated by Django 5.1.7 on 2025-03-30 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_patientdischargedetails_total_lab_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtest',
            name='cost',
        ),
    ]
