# Generated by Django 5.1.7 on 2025-03-31 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_rename_lab_results_patientdischargedetails_lab_test_result_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdischargedetails',
            name='lab_test_cost',
        ),
        migrations.RemoveField(
            model_name='patientdischargedetails',
            name='lab_test_name',
        ),
        migrations.RemoveField(
            model_name='patientdischargedetails',
            name='lab_test_result',
        ),
        migrations.AddField(
            model_name='patientdischargedetails',
            name='total_lab_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='LabTest',
        ),
    ]
