# Generated by Django 5.1.7 on 2025-03-31 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_remove_patientdischargedetails_lab_test_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(choices=[('CBC', 'Complete Blood Count (CBC)'), ('LFT', 'Liver Function Test (LFT)'), ('KFT', 'Kidney Function Test (KFT)'), ('BS', 'Blood Sugar Test'), ('THY', 'Thyroid Function Test'), ('COVID', 'COVID-19 RT-PCR'), ('LIPID', 'Lipid Profile Test')], max_length=50)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='lab_reports/')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.patient')),
            ],
        ),
    ]
