# Generated by Django 5.1.7 on 2025-03-31 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_labtestbooking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labtestbooking',
            old_name='report_file',
            new_name='report',
        ),
        migrations.RemoveField(
            model_name='labtestbooking',
            name='payment_status',
        ),
        migrations.AlterField(
            model_name='labtestbooking',
            name='test_name',
            field=models.CharField(max_length=255),
        ),
    ]
