# Generated by Django 5.1.7 on 2025-03-31 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_rename_report_file_labtestbooking_report_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LabTestBooking',
        ),
    ]
