# Generated by Django 5.1.7 on 2025-03-31 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_delete_labtestbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='cost',
        ),
    ]
