# Generated by Django 5.1.7 on 2025-03-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_remove_prescription_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
