# Generated by Django 5.1.7 on 2025-03-31 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_prescription_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdischargedetails',
            name='prescribed_medicines',
        ),
    ]
