# Generated by Django 5.1.7 on 2025-03-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_labtestbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtestbooking',
            name='booking_date',
            field=models.DateTimeField(),
        ),
    ]
