# Generated by Django 5.1.7 on 2025-04-02 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_labtestprescription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LabTestPrescription',
        ),
    ]
