# Generated by Django 5.1.7 on 2025-04-02 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_labtestprescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtestbooking',
            name='test_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.labtestprescription'),
        ),
    ]
