# Generated by Django 5.1.7 on 2025-04-02 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_remove_labtestprescription_doctor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(choices=[('Blood Test', 'Blood Test'), ('X-Ray', 'X-Ray'), ('MRI Scan', 'MRI Scan'), ('CT Scan', 'CT Scan'), ('Urine Test', 'Urine Test'), ('ECG', 'ECG')], max_length=255)),
                ('booking_date', models.DateTimeField()),
                ('report', models.FileField(blank=True, null=True, upload_to='lab_reports/')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.patient')),
            ],
        ),
        migrations.CreateModel(
            name='LabTestPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(choices=[('Blood Test', 'Blood Test'), ('X-Ray', 'X-Ray'), ('MRI Scan', 'MRI Scan'), ('CT Scan', 'CT Scan'), ('Urine Test', 'Urine Test'), ('ECG', 'ECG')], max_length=255)),
                ('prescription_date', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.patient')),
            ],
        ),
    ]
